### ISSUE TITLE
Output msg type

### ISSUE THREAD

**Issue by dorkamotorka** [usrl-uofsc/stag_ros#10]
https://github.com/usrl-uofsc/stag_ros/blob/f1b88c5a9a4c1de61a501f804e1870007ea6436c/src/stag_ros/stag_node.cpp#L73

Assuming the output msg type is geometry_msgs::PoseStamped this means that each detected marker is published(outputed) separately. 

I think it would be better if the detected markers would be combined into an array that is published. This makes stuff easier for example if one wants to determine which markers is the closest one or how many markers is detected etc.

vision_msgs does offer Detection2DArray as also Detection2D which might be useful in this case, if you consider it.

**Comment by MikeK4y** [comment]
This issue sparked a debate. We ended up going with a custom message for a single marker/bundle and then publishing as an array. Let us know if that works for you or if you have any other recommendations.
