### ISSUE TITLE
Issue with Pose Accuracy 

### ISSUE THREAD

**Issue by udit7395** [usrl-uofsc/stag_ros#13]
I am trying to localize the [OAK-D camera](https://docs.luxonis.com/projects/hardware/en/latest/pages/BW1098OAK.html) w.r.t to a STAG marker. I know the library assumes a USB camera and hence I have modified the stagNode.cpp so that it works with OAK-D (the distortion matrix has more values compared to a normal USB cam). I am using the monocular camera from OAK-D at 720p 60fps and the marker detection works as expected. But when I print out the pose, the values are way off, for eg, when the marker is 1.5 meters away the z value is 1.3meters. I have ensured the config file is correct. I  I am uam using libraryHD 23 with error correction of 11. My marker side is 16.1 cm, so the config corners are as follows
tags:
  [
    {
      frame: "single_config_test",
      id: 0,
      corners: [
        [-0.0805,0.0805,0.0],
        [0.0805,0.0805,0.0],
        [0.0805,-0.0805,0.0],
      ]
    }
  ]
bundles:
  [
  ]

Any idea of what I might be doing wrong? 

If you need any more information, please let me know. 
Thanks.

**Comment by MikeK4y** [comment]
What is the camera model you are using? The package assumes you are using a pinhole camera model. [If you are using a fisheye model then you have to undistort the marker points before using them in solvePnP](https://stackoverflow.com/questions/59062410/how-can-i-solvepnp-with-fisheye-camera-parameters)

**Comment by udit7395** [comment]
@MikeK4y Thanks for the quick reply. I have checked the documentation and verified its not a fish eye lens.

**Comment by MikeK4y** [comment]
If you can upload your config files and a bag file with a few seconds of data I can take a look and try to figure out what's wrong

**Comment by udit7395** [comment]
Sure
The marker is at distance of 1.7 meter from the camera. 
The [files requested](https://drive.google.com/drive/folders/1zbJV8koYmFY2dpPSqngt1ITZSiAVrhSC?usp=sharing) can be found here. If you visualize the images, the pink dot is the center of the image. Also, you might see some white dot on the marker, that's me measuring the distance to the marker using laser distance meter.

Thank you very much for your help And Please let me know if you need anything else.

**Comment by udit7395** [comment]
One more update. I tried using the my laptop camera, calibrated it and still I am getting a similar result. The Z value seems to be off 15-20 cm

**Comment by MikeK4y** [comment]
I checked the file and you are using a different distortion model than the one we were assuming. However it is supported by OpenCV so I just had to allow the distortion matrix to change size to accommodate the different model. The last commit addresses this.

Running the package with your files I am getting a distance of 1.55 - 1.6 meters. Assuming that the marker size and camera calibration are correct, the few centimetres of error are within the expected accuracy.

How confident are you in your ground truth? Especially since you have around the same error with 2 different cameras.

**Comment by udit7395** [comment]
I have high certainty in my ground truth as I am using a laser distance meter. Also could you tell what accuracy should I expect ?  For eg if z is 1.0m, what would be the acceptable range of output for position z ?

**Comment by MikeK4y** [comment]
You can read the paper in the README for information on the expected accuracy.

15-20cm is definitely unexpectedly high. Since you are using a depth camera what does the camera say about the distance to the marker?

**Comment by udit7395** [comment]
I haven't tested in that mode. I am just using one of the depth cameras since they have global shutter and high fps compared to the RGB cameras but I shall test and will report back. Thank you for your help.

**Comment by udit7395** [comment]
@MikeK4y So I rechecked my ground truth with the old measurement tapes and it was off. My bad. Once again thank you for all your help. I am marking this issue as closed now.

**Comment by MikeK4y** [comment]
@udit7395  Glad I could help

Also now the package supports other distortion models so thanks for bringing this up
