### ISSUE TITLE
REQUIRED process [download_bags-2] has died!

### ISSUE THREAD

**Issue by emretasar02** [usrl-uofsc/stag_ros#16]
![Screenshot from 2022-09-26 11-23-01](https://user-images.githubusercontent.com/62650978/192229161-6d81fff6-8102-4367-bf51-c6e1a1575708.png)

**Comment by MikeK4y** [comment]
The download_examples.launch file is supposed to download the sample bag files and then exit. From the screenshot it looks like it did just that
