### ISSUE TITLE
/stag_ros/markers vs /stag_ros/bundles?

### ISSUE THREAD

**Issue by irsyadtc** [usrl-uofsc/stag_ros#17]
Please explain to me what is/are the difference(s) of /stag_ros/markers topic and /stag_ros/bundles topic? Both of them have the same message type, stag_ros/STagMarker[]

**Comment by MikeK4y** [comment]
The pose information about individual markers is published in the /stag_ros/markers and pose information about marker bundles is published in /stag_ros/bundles. You can set up which markers are to be used individually and which ones are part of a bundle using a config file like [this for bundles](https://github.com/usrl-uofsc/stag_ros/blob/noetic-devel/cfg/bundle_config_2.yaml) and [this for individuals](https://github.com/usrl-uofsc/stag_ros/blob/noetic-devel/cfg/bundle_config_single.yaml)

**Comment by irsyadtc** [comment]
Thank you for the response. I have two more questions:
- if I wanted to publish multiple markers as individuals, then this means that each marker has its own "frame:" in the yaml file. Is this right? e.g:
```YAML
tags:
  [
    {
     frame: "tag_7",
      id: 7,
      corners: [
      	[-0.127,  0.059, 0.0],
        [-0.009,  0.059, 0.0],
        [-0.009, -0.059, 0.0]
        ]
        },
    {
      frame: "tag_1",
      id: 1,
      corners : [
        [0.009,  0.059, 0.0],
        [0.127,  0.059, 0.0],
        [0.127, -0.059, 0.0]
        ]
    }    
  ]
bundles:
  [
  ]
```

- How do I define the corner values?

**Comment by MikeK4y** [comment]
Check #8

**Comment by irsyadtc** [comment]
Thank you for the link.
