### ISSUE TITLE
False package name in the download_examples.launch

### ISSUE THREAD

**Issue by dorkamotorka** [usrl-uofsc/stag_ros#2]
https://github.com/usrl-uofsc/stag_ros/blob/f5f44dad4a29ada34468722d3705b529b54ad539/launch/download_examples.launch#L3

ros_tellopy should be replaced with stag_ros, because obviously that's the name of the package.

**Comment by dorkamotorka** [comment]
I guess that implies also to the melodic-devel and noetic-devel branch.

**Comment by MikeK4y** [comment]
Fixed. Thanks for catching this!
