### ISSUE TITLE
Configuration files parameters

### ISSUE THREAD

**Issue by dorkamotorka** [usrl-uofsc/stag_ros#8]
What does those two in the .cfg files means(both theoretically and in terms of practice - should user ever changed it?):
- errorCorrection
- corners (array)

**Comment by Brenn10** [comment]
The error correction is at max half the minimum hamming distance. So if you would like to allow for error correction for a hamming distance of 15, the error correction must be 7 or lower. This is the number of wrong bits in the code which may be corrected. In practice, a lower number will lead to fewer false detections, whereas a higher number will allow a tag to be detected more easily.

Corners specifies the size and position of the tag. This is important for differently sized tags and bundles of tags. The order of the corners is that it starts at the tag label (HD,ID) and goes clockwise. Only three need to be provided and should create a square. Positive x is to the right and positive y is up in the plane of the tag with the z axis coming out of the tag.

![image](https://user-images.githubusercontent.com/8217972/101505153-089c0700-3942-11eb-8642-8d0556afb286.png)

I am closing the issue. If I didn't answer your question, please reopen it.

**Comment by mrunaljsarvaiya** [comment]
@Brenn10  Is the origin in the center of the tag?

**Comment by Brenn10** [comment]
> @Brenn10  Is the origin in the center of the tag?

The origin is essentially the corner labeled 0 (the corner with the ID). You can also set any arbitrary origin if you would like and define the distance to each corner in your config.

The corners of a 2m wide tag with the center being the origin would look like the following (tuples are x, y, z) :
(-1,1,0), (1,1,1), (1,-1,0), (-1,-1,0)

Typing on my phone, so forgive the brevity. Feel free to comment again if you have additional questions. You can also open a new issue if you have a question that others may also have.

**Comment by mrunaljsarvaiya** [comment]
> > @Brenn10  Is the origin in the center of the tag?
> 
> The origin is essentially the corner labeled 0 (the corner with the ID). You can also set any arbitrary origin if you would like and define the distance to each corner in your config.
> 
> The corners of a 2m wide tag with the center being the origin would look like the following (tuples are x, y, z) : (-1,1,0), (1,1,1), (1,-1,0), (-1,-1,0)
> 
> Typing on my phone, so forgive the brevity. Feel free to comment again if you have additional questions. You can also open a new issue if you have a question that others may also have.

Thanks! Appreciate the quick response
